### ISSUE TITLE
Requested for rds connecton with java application in aws

### ISSUE THREAD

**Issue by GiridharGada** [awslabs/rds-support-tools#34]
Hi Sir,

I am new for aws, i am tnot able to connect java application with rds in aws. 
So I am requesting you to please provide one simple example and what procedue, so  i can do .

Thanks and Regards
Giridhar

**Comment by goeringk** [comment]
Hello Giridhar,

In response to your request for an example of a java application connecting to RDS, you can find it now here:
[RDSDatabaseConnection.java](https://github.com/awslabs/rds-support-tools/blob/master/mysql/diag/shell/RDSDatabaseConnection.java)

This example is geared towards MySQL using JDBC. Be sure to read the description in the [mysql.README](https://github.com/awslabs/rds-support-tools/blob/master/mysql/mysql.README) for a better description and run as information. I hope this helps!

Regards,
~Kevin
