### ISSUE TITLE
Lambda handler

### ISSUE THREAD

**Issue by tammyllf** [awslabs/rds-support-tools#80]
Hi,

This code work perfectly in local machine and push to S3 bucket.
However, I would like to deploy this to aws lambda function, however, I don't seem able to solve the lambda_handler name issue.
Appreciate, if you could help.

**Comment by deanah** [comment]
Here is a demo for connecting to AWS dbs from a URL (i.e. connecting from API Gateway via Lambda):. There is an extensive guidance section:  https://aws.amazon.com/blogs/database/query-your-aws-database-from-your-serverless-application/

**Comment by tammyllf** [comment]
Hi Deanah,

Thanks for the suggestion, 
I'm new to lambda function, and not familiar with API gateway via Lambda.
Any alternative suggestion from you? Lambda function would be my priority choice.

Thanks

**Comment by deanah** [comment]
API Gateway is just one way to invoke Lambda. This is the best choice if you want to do something like query the database by clicking on a link on your static website.

You can use the invocation method of your choice.

**Comment by tammyllf** [comment]
Hi Deanah,

I found solution for this, thanks for sharing.
